# Generated by Django 4.0.1 on 2022-10-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='ip',
            field=models.TextField(default=' '),
        ),
    ]
